/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_hello_MyApplication
#define _Included_com_example_hello_MyApplication
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_example_hello_MyApplication_run
  (JNIEnv *,jclass myclass, jobject, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
